app = "bitcoinwhistlex"
primary_region = "iad"

[build]
dockerfile = "Dockerfile"

[env]
NODE_ENV = "production"

[[services]]
  internal_port = 3000
  protocol = "tcp"
  auto_stop_machines = "off"

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
